zalando-stups/yourturn

LICENSE, MAINTAINERS, README.md, package.json
Add MAINTAINERS, LICENSE file, update README
=> Meet our OSS requirements as specified in GDocs

client/lib/application/src/data/api-actions.js, client/lib/application/src/data/api-store.js, client/lib/application/src/detail/app-detail.hbs, client/lib/application/src/detail/app-detail.js, client/lib/application/src/detail/placeholder.hbs, client/lib/application/src/flux.js, client/lib/application/src/router.js, client/lib/common/asset/scss/variables.scss, client/lib/common/src/base-view.js, client/webpack.config.js, client/webpack.production.config.js, package.json, server/mocks/twintip.js
=> Twintip link

Dockerfile, client/Gulpfile.js, client/index.html, package.json
=> #19 bust the cache

client/lib/application/src/router.js, client/lib/application/src/version-detail/placeholder.hbs, client/lib/application/src/version-detail/version-detail.hbs, client/lib/application/src/version-detail/version-detail.js, client/lib/application/src/version-form/version-form.hbs, client/lib/application/src/version-form/version-form.js, client/lib/application/src/version-list/version-list.hbs, client/lib/application/src/version-list/version-list.js, client/lib/common/asset/scss/application/version-detail.scss, client/lib/common/asset/scss/application/version-form.scss
=> Edit app version

client/lib/application/src/application-detail/application-detail.hbs, client/lib/application/src/application-detail/application-detail.js, client/lib/application/src/application-detail/placeholder.hbs, client/lib/application/src/router.js, client/lib/common/asset/scss/application/application-detail.scss, client/lib/yourturn/src/sidebar/sidebar.hbs
=> Version click flow

client/lib/application/src/approval-form/approval-card/approval-card.hbs, client/lib/common/asset/scss/application/approval-card.scss, client/lib/common/src/data/application/application-store.js, client/lib/common/src/data/resource/resource-store.js
=> Application sorting

client/lib/application/src/application-detail/application-detail.js, client/lib/application/src/application-form/application-form.js, client/lib/application/src/application-list/application-list.js, client/lib/application/src/approval-form/approval-form.js, client/lib/application/src/flux.js, client/lib/application/src/oauth-form/oauth-form.js, client/lib/application/src/router.js, client/lib/application/src/version-detail/version-detail.js, client/lib/application/src/version-form/version-form.js, client/lib/application/src/version-list/version-list.js, client/lib/common/src/data/application/application-actions.js, client/lib/resource/src/create-resource/create-resource.js, client/lib/resource/src/create-scope/create-scope.js, client/lib/resource/src/flux.js, client/lib/resource/src/resource-detail/resource-detail.js, client/lib/resource/src/resource-list/resource-list.js, client/lib/resource/src/router.js, client/lib/resource/src/scope-detail/scope-detail.js, client/lib/yourturn/src/bootstrap.js, client/lib/yourturn/src/flux.js, client/lib/yourturn/src/notification-bar/notification-bar.js, client/lib/yourturn/src/router.js
=> Refactor view api

client/lib/application/src/application-detail/application-detail.hbs, client/lib/application/src/application-form/application-form.hbs, client/lib/application/src/application-form/application-form.js, client/lib/application/src/oauth-form/searchable-list/contains.js, client/lib/application/src/version-form/version-form.hbs, client/lib/application/src/version-form/version-form.js, client/lib/common/asset/scss/application/application-form.scss, client/lib/common/asset/scss/application/version-form.scss, client/lib/common/asset/scss/resource/resource-form.scss, client/lib/common/src/data/resource/resource-actions.js, client/lib/common/src/data/resource/resource-store.js, client/lib/common/src/data/services.js, client/lib/common/src/handlebars/contains.js, client/lib/common/test/resource/resource-store.test.js, client/lib/resource/src/create-scope/create-scope.js, client/lib/resource/src/resource-detail/placeholder.hbs, client/lib/resource/src/resource-detail/resource-detail.hbs, client/lib/resource/src/resource-detail/resource-detail.js, client/lib/resource/src/resource-form/resource-form.hbs, client/lib/resource/src/resource-form/resource-form.js, client/lib/resource/src/router.js, client/webpack.config.js, server/mocks/essentials.js
=> Edit resource types

client/lib/application/src/version-form/version-form.js
=> Remove application_id from version json body

client/lib/application/src/approval-form/approval-form.hbs, client/lib/application/src/approval-form/approval-form.js, client/lib/application/src/router.js, client/lib/common/src/data/application/application-actions.js, client/lib/common/src/data/application/application-store.js, server/mocks/kio.js
=> Display custom approval types in selectbox

client/lib/application/src/access-form/access-form.js, client/lib/application/src/oauth-form/oauth-form.js, client/lib/resource/src/resource-detail/resource-detail.js
=> Filter scopes correctly

client/lib/resource/src/resource-form/resource-form.hbs
=> Rename applications to services

client/lib/application/src/application-form/application-form.js, client/lib/application/src/version-form/version-form.js, client/lib/common/src/data/user/user-actions.js, client/lib/common/src/searchable-list/searchable-list.js, client/lib/resource/src/resource-form/resource-form.js, client/lib/resource/src/scope-form/scope-form.js, client/webpack.config.js, client/webpack.production.config.js, client/webpack.test.config.js
=> Development config

client/Gulpfile.js, client/lib/common/src/data/user/user-store.js, client/lib/common/src/lodash.custom.js, client/lib/common/test/user/user-store.test.js, server/mocks/5005-team.js
=> Dedup and sort userteams

client/lib/application/src/application-detail/application-detail.hbs, client/lib/application/src/application-detail/placeholder.hbs, server/mocks/5000-kio.js
=> Show spec url of application

client/lib/application/src/access-form/access-form.hbs, client/lib/application/src/access-form/placeholder.hbs, client/lib/application/src/application-detail/application-detail.hbs, client/lib/application/src/application-detail/placeholder.hbs, client/lib/application/src/application-form/application-form.hbs, client/lib/application/src/application-list/application-list.hbs, client/lib/application/src/approval-form/approval-form.hbs, client/lib/application/src/oauth-form/oauth-form.hbs, client/lib/application/src/oauth-form/placeholder.hbs, client/lib/application/src/version-detail/placeholder.hbs, client/lib/application/src/version-detail/version-detail.hbs, client/lib/application/src/version-form/version-form.hbs, client/lib/application/src/version-list/version-list.hbs, client/lib/resource/src/resource-detail/placeholder.hbs, client/lib/resource/src/resource-detail/resource-detail.hbs, client/lib/resource/src/resource-form/resource-form.hbs, client/lib/resource/src/scope-detail/placeholder.hbs, client/lib/resource/src/scope-detail/scope-detail.hbs, client/lib/resource/src/scope-form/scope-form.hbs, client/lib/yourturn/src/search/search.hbs
=> Improve navigation

client/lib/common/src/data/user/user-store.js, client/lib/common/test/user/user-store.test.js
=> Delete code for team service workaround

server/yourturn.js
=> Read client id from environment, if applicable

client/lib/application/src/application-detail/application-detail.hbs, client/lib/application/src/application-list/application-list.hbs, client/lib/application/src/version-detail/version-detail.hbs, client/lib/common/asset/scss/application/application-detail.scss, client/lib/common/asset/scss/application/application-list.scss, client/lib/common/asset/scss/application/version-detail.scss, client/lib/common/asset/scss/base.scss, client/lib/common/asset/scss/resource/resource-detail.scss, client/lib/common/asset/scss/resource/scope-detail.scss, client/lib/common/asset/scss/variables.scss, client/lib/resource/src/resource-detail/resource-detail.hbs, client/lib/resource/src/scope-detail/scope-detail.hbs
=> Markdown max width

client/lib/application/src/access-form/access-form.hbs, client/lib/application/src/access-form/access-form.js, client/lib/application/src/approval-form/approval-card/approval-card.js, client/lib/application/src/oauth-form/oauth-form.hbs, client/lib/application/src/oauth-form/oauth-form.js, client/lib/application/src/oauth-sync-info.hbs, client/lib/application/src/version-form/version-form.hbs, client/lib/common/asset/scss/application/access-form.scss, client/lib/common/asset/scss/application/oauth-sync-info.scss, client/lib/common/asset/scss/base.scss, client/lib/common/asset/scss/button.scss, client/lib/common/asset/scss/form.scss, client/lib/common/src/config.js, client/lib/common/src/handlebars/absoluteDate.js, client/lib/common/src/handlebars/relativeDate.js, client/lib/resource/src/resource-list/resource-list.hbs, server/mocks/5004-mint.js
=> Mint status info

client/lib/application/src/approval-form/approval-form.hbs, client/lib/application/src/approval-form/approval-form.js, client/lib/application/test/approval-form.test.js
=> Explain default approval types

client/lib/application/src/version-form/version-form.hbs, client/lib/common/asset/scss/application/editable-list.scss, client/lib/common/asset/scss/form.scss, client/lib/common/asset/scss/yourturn/search.scss, client/lib/resource/src/resource-list/resource-list.hbs, client/lib/resource/src/scope-form/scope-form.hbs, client/lib/yourturn/src/search/search.hbs, server/mocks/5005-team.js
=> Fix regresssions

client/lib/application/src/application-detail/application-detail.hbs, client/lib/application/src/application-detail/placeholder.hbs, client/lib/application/src/version-detail/version-detail.hbs, client/lib/common/src/data/application/application-store.js, client/lib/common/test/application/application-store.test.js, server/mocks/5000-kio.js
=> App version last modified

client/.eslintrc, client/lib/application/src/application-list/application-list.hbs, client/lib/application/src/version-list/version-list.hbs, client/lib/application/src/version-list/version-list.js, client/lib/application/test/application-list.test.js, client/lib/application/test/version-list.test.js, client/lib/common/asset/scss/application/version-list.scss, client/lib/common/src/data/application/application-store.js, client/lib/common/test/application/application-store.test.js, client/lib/resource/src/resource-list/resource-list.hbs, client/lib/resource/src/router.js, client/lib/resource/test/resource-list.test.js
=> Search app versions

client/lib/application/src/application-form/application-form.hbs, client/lib/application/src/application-form/application-form.js
=> Unrequire service url

client/index.html, client/lib/application/src/flux.js, client/lib/application/src/router.js, client/lib/application/src/version-detail/version-detail.hbs, client/lib/application/src/version-detail/version-detail.js, client/lib/application/test/version-detail.test.js, client/lib/common/asset/scss/application/version-detail.scss, client/lib/common/asset/scss/base.scss, client/lib/common/src/data/pierone/pierone-actions.js, client/lib/common/src/data/pierone/pierone-store.js, client/lib/common/src/data/services.js, client/lib/common/test/bootstrap.js, client/lib/common/test/pierone/pierone-actions.test.js, client/lib/common/test/pierone/pierone-store.test.js, server/mocks/5000-kio.js, server/mocks/5007-pierone.js
=> scm source warnings

Dockerfile, server/yourturn.js
=> GZIP and cache headers

client/lib/application/src/version-detail/version-detail.hbs, server/mocks/5007-pierone.js
=> If scmSource is fetchresult, display spinner

client/Gulpfile.js, client/index-prod.html, package.json
=> Inline above the fold css

client/lib/application/src/access-form/access-form.hbs, client/lib/application/src/access-form/access-form.js, client/lib/application/src/access-form/placeholder.hbs, client/lib/application/src/application-detail/application-detail.hbs, client/lib/application/src/application-detail/application-detail.js, client/lib/application/src/application-detail/placeholder.hbs, client/lib/application/src/approval-form/approval-form.hbs, client/lib/application/src/approval-form/approval-form.js, client/lib/application/src/oauth-form/oauth-form.hbs, client/lib/application/src/oauth-form/oauth-form.js, client/lib/application/src/router.js, client/lib/application/src/version-detail/placeholder.hbs, client/lib/application/src/version-detail/version-detail.hbs, client/lib/application/src/version-detail/version-detail.js, client/lib/application/test/access-form.test.js, client/lib/application/test/application-detail.test.js, client/lib/application/test/approval-form.test.js, client/lib/application/test/oauth-form.test.js, client/lib/application/test/version-detail.test.js
=> Write access only for own apps

client/lib/application/src/application-detail/application-detail.hbs, client/lib/application/src/application-detail/placeholder.hbs, client/lib/application/src/version-detail/placeholder.hbs, client/lib/application/src/version-detail/version-detail.hbs, client/lib/application/src/version-list/version-list.hbs, client/lib/application/test/version-list.test.js, client/lib/common/asset/less/application/application-detail.less, client/lib/common/asset/less/application/version-detail.less, client/lib/common/asset/less/application/version-list.less, client/lib/common/asset/less/base.less, client/lib/common/asset/less/button.less, client/lib/common/asset/less/resource/resource-detail.less, client/lib/common/asset/less/resource/scope-detail.less, client/lib/resource/src/resource-detail/placeholder.hbs, client/lib/resource/src/resource-detail/resource-detail.hbs, client/lib/resource/src/scope-detail/placeholder.hbs, client/lib/resource/src/scope-detail/scope-detail.hbs
=> New version link

client/lib/application/src/router.react.jsx, client/lib/common/src/data/user/user-actions.js, client/lib/common/src/util.js, client/lib/violation/src/router.react.jsx, client/lib/yourturn/src/sidebar/sidebar.jsx
=> Fetch access token in requireTeam()

client/lib/yourturn/src/validate-oauth-response.js, client/lib/yourturn/test/bootstrap.js, client/lib/yourturn/test/validate-oauth-response.test.js, client/webpack.test.config.js
=> Leading slash in realm

client/lib/application/src/application-form/application-form.jsx
=> Support ip address in service url

client/lib/application/src/approval-form/approval-form.jsx, client/lib/application/test/approval-form.test.js, client/lib/common/asset/less/button.less
=> Approval form button

client/lib/application/src/application-form/application-form.jsx, client/lib/application/src/approval-form/approval-form.jsx
=> Fix placeholder

client/lib/application/src/application-detail/application-detail.jsx, client/lib/application/src/application-detail/placeholder.jsx, client/lib/application/src/application-form/application-form.jsx, client/lib/application/test/application-form.test.js, client/lib/common/asset/less/form.less, server/mocks/5000-kio.js
=> Add required approvers

README.md, client/lib/application/src/application-list/application-list.jsx, client/lib/common/asset/less/application/application-list.less
=> Inactive apps overview

README.md, client/lib/yourturn/src/router.react.jsx
=> Fix Gravatar loading

client/lib/common/asset/less/base.less, client/lib/common/asset/less/violation/violation-card.less, client/lib/common/asset/less/violation/violation-detail.less, client/lib/common/asset/less/violation/violation-list.less, client/lib/common/src/data/fullstop/fullstop-actions.js, client/lib/common/src/data/fullstop/fullstop-store.js, client/lib/common/src/data/user/user-actions.js, client/lib/common/src/data/user/user-store.js, client/lib/common/test/fullstop/fullstop-actions.test.js, client/lib/common/test/fullstop/fullstop-store.test.js, client/lib/common/test/user/user-store.test.js, client/lib/violation/src/router.react.jsx, client/lib/violation/src/violation-card/violation-card.jsx, client/lib/violation/src/violation-detail/violation-detail.jsx, client/lib/violation/src/violation-list/violation-list.jsx, server/mocks/5005-team.js
=> Link to single violation

client/lib/common/asset/less/common/datepicker.less, client/lib/common/asset/less/violation/violation-list.less, client/lib/common/src/config.js, client/lib/common/src/data/fullstop/fullstop-actions.js, client/lib/common/src/data/fullstop/fullstop-store.js, client/lib/common/src/data/user/user-store.js, client/lib/common/src/datepicker.jsx, client/lib/common/test/fullstop/fullstop-store.test.js, client/lib/resource/src/resource-form/resource-form.jsx, client/lib/violation/src/router.react.jsx, client/lib/violation/src/violation-list/violation-list.jsx, server/mocks/5008-fullstop.js
=> Violation Browsing

client/lib/application/src/approval-form/approval-form.jsx, client/lib/application/test/approval-form.test.js, client/lib/common/asset/less/application/approval-form.less, client/lib/common/asset/less/button.less, client/lib/common/asset/less/yourturn/sidebar.less, client/mocha-globals.js, package.json
=> Approval UX

client/Gulpfile.js, client/lib/application/src/application-list/application-list.jsx, client/lib/application/src/router.react.jsx, client/lib/application/src/version-form/version-form.jsx, client/lib/application/test/application-list.test.js, client/lib/common/asset/less/application/application-list.less, client/lib/common/asset/less/base.less, client/lib/common/src/data/kio/kio-store.js, client/lib/common/src/lodash.custom.js, client/lib/common/src/util.js, client/lib/common/test/kio/kio-store.test.js
=> Improve application list UX

client/lib/application/src/application-form/application-form.jsx
=> Disallow capital letters

client/lib/application/src/access-form/access-form.jsx, client/lib/application/src/application-detail/application-detail.jsx, client/lib/application/src/application-form/application-form.jsx, client/lib/application/src/application-list/application-list.jsx, client/lib/application/src/approval-form/approval-form.jsx, client/lib/application/src/oauth-form/oauth-form.jsx, client/lib/application/src/router.react.jsx, client/lib/application/src/version-detail/version-detail.jsx, client/lib/application/test/application-form.test.js, client/lib/application/test/application-list.test.js, client/lib/application/test/approval-form.test.js, client/lib/common/src/data/user/user-actions.js, client/lib/common/src/data/user/user-store.js, client/lib/common/src/util.js, client/lib/common/test/user/user-store.test.js, client/lib/yourturn/src/bootstrap.jsx, client/lib/yourturn/src/router.react.jsx, client/lib/yourturn/src/validate-oauth-response.js, client/lib/yourturn/test/validate-oauth-response.test.js, server/mocks/5005-team.js, server/yourturn.js
=> Update team service api

client/lib/application/src/oauth-sync-info.jsx, client/lib/common/asset/less/application/oauth-sync-info.less
=> #202 add warning when mint has problems

Dockerfile, client/index-prod.html, server/yourturn.js
=> Appdynamics support

client/lib/application/src/application-form/application-form.jsx, client/lib/application/src/application-list/application-list.jsx, client/lib/application/src/approval-form/approval-form.jsx, client/lib/application/src/router.react.jsx, client/lib/application/test/application-form.test.js, client/lib/application/test/application-list.test.js, client/lib/application/test/approval-form.test.js, client/lib/common/src/data/user/user-actions.js, client/lib/common/src/data/user/user-store.js, client/lib/common/src/util.js, client/lib/common/test/user/user-store.test.js, client/lib/violation/src/violation-list/violation-list.jsx, client/lib/yourturn/src/bootstrap.jsx, client/lib/yourturn/src/router.react.jsx, server/mocks/5005-team.js, server/yourturn.js
=> Use accounts instead of teams

client/lib/application/src/application-form/application-form.jsx
=> Default team_id value should be account name

client/index-prod.html
=> Fix monitorings

client/lib/common/src/data/user/user-actions.js, client/lib/common/src/data/user/user-store.js, client/lib/common/src/util.js, client/lib/common/test/user/user-store.test.js, client/lib/yourturn/src/bootstrap.jsx, client/lib/yourturn/src/router.react.jsx, client/lib/yourturn/src/validate-oauth-response.js, client/lib/yourturn/test/validate-oauth-response.test.js, server/mocks/5005-team.js, server/yourturn.js
=> Check for cloud accounts always

client/lib/common/asset/less/application/approval-form.less, client/lib/common/asset/less/base.less, client/lib/common/asset/less/violation/violation-list.less, client/lib/common/src/data/fullstop/fullstop-store.js, client/lib/common/src/data/team/team-actions.js, client/lib/common/src/data/team/team-store.js, client/lib/common/test/bootstrap.js, client/lib/common/test/fullstop/fullstop-store.test.js, client/lib/common/test/team/team-actions.test.js, client/lib/common/test/team/team-store.test.js, client/lib/violation/src/flux.js, client/lib/violation/src/router.react.jsx, client/lib/violation/src/violation-card/violation-card.jsx, client/lib/violation/src/violation-list/violation-list.jsx, client/lib/violation/test/bootstrap.js, client/lib/violation/test/violation-list.test.js, client/webpack.test.config.js, package.json, server/mocks/5005-team.js, server/mocks/fullstop-violations.json, server/yourturn.js
=> View all account's violations

client/lib/common/src/data/kio/kio-actions.js, server/yourturn.js
=> Fix Auditing field bug

client/lib/application/src/oauth-sync-info.jsx, server/mocks/5004-mint.js
=> display mint message

client/lib/application/src/access-form/access-form.jsx, client/lib/application/src/oauth-form/oauth-form.jsx, client/lib/application/src/oauth-sync-info.jsx, client/lib/common/asset/less/application/oauth-sync-info.less, client/lib/common/src/data/mint/mint-actions.js, server/mocks/5004-mint.js
=> renew credentials button

client/lib/common/src/data/essentials/essentials-actions.js, client/lib/common/src/data/fullstop/fullstop-actions.js, client/lib/common/src/data/kio/kio-actions.js, client/lib/common/src/data/mint/mint-actions.js, client/lib/common/src/data/pierone/pierone-actions.js, client/lib/common/src/data/search/search-actions.js, client/lib/common/src/data/team/team-actions.js, client/lib/common/src/data/twintip/twintip-actions.js, client/lib/common/src/data/user/user-actions.js, server/yourturn.js
=> #234 always accept gzip

client/lib/application/src/application-form/application-form.jsx
=> allow team edit

client/lib/application/src/application-form/application-form.jsx, client/lib/application/test/application-form.test.js
=> no create without team

client/lib/application/src/application-form/application-form.jsx
=> service_url might be null

client/lib/application/src/application-form/application-form.jsx
=> #248 do not change teamid

.travis.yml, client/lib/application/src/application-list/application-list.jsx, client/lib/common/src/data/kio/kio-store.js, client/lib/common/src/fetch-result.js, client/lib/common/test/kio/kio-store.test.js, package.json
=> immutable kio store

.travis.yml, client/lib/application/src/application-detail/application-detail.jsx, client/lib/application/src/application-list/application-list.jsx, client/lib/application/src/version-detail/version-detail.jsx, client/lib/common/asset/less/base.less, client/lib/common/src/data/kio/kio-store.js, client/lib/common/test/kio/kio-store.test.js, client/lib/violation/src/violation-card/violation-card.jsx, client/lib/violation/src/violation-list/violation-list.jsx
=> app list ux

client/Gulpfile.js, client/lib/application/src/access-form/access-form.jsx, client/lib/application/src/editable-list.jsx, client/lib/common/asset/less/application/access-form.less, client/lib/common/src/data/mint/mint-store.js, client/lib/common/src/lodash.custom.js
=> better bucket ux

client/lib/resource/src/resource-form/resource-form.jsx, client/lib/resource/src/scope-form/scope-form.jsx
=> fix regexes for essentials

client/lib/common/src/data/user/user-store.js
=> immutable user

client/lib/common/src/data/search/search-store.js
=> immutable search

client/lib/common/src/data/twintip/twintip-store.js
=> immutable twintip

client/lib/common/src/data/team/team-store.js
=> immutable team

client/lib/common/src/data/pierone/pierone-store.js
=> immutable pierone

client/lib/common/src/data/notification/notification-store.js
=> immutable notifications

client/lib/common/src/data/essentials/essentials-store.js, client/lib/common/test/essentials/essentials-store.test.js
=> immutable essentials

client/lib/common/src/data/fullstop/fullstop-store.js
=> transition fullstop store to immutablejs

package.json
=> #277 drop mori

client/lib/application/src/access-form/access-form.jsx, client/lib/application/src/oauth-form/oauth-form.jsx
=> make scopes selectable again

client/lib/common/src/data/essentials/essentials-store.js, client/lib/resource/src/router.react.jsx, client/lib/resource/src/scope-detail/scope-detail.jsx, client/lib/resource/test/scope-detail.test.js
=> 270 scope detail apps

client/lib/violation/src/violation-card/violation-card.jsx
=> #295 fix bug with always current date in violations

client/lib/common/src/data/fullstop/fullstop-actions.js, client/lib/common/src/data/fullstop/fullstop-getter.js, client/lib/common/src/data/fullstop/fullstop-store.js, client/lib/common/src/data/fullstop/fullstop-types.js, client/lib/common/test/fullstop/fullstop-store.test.js
=> #283 redux-ify fullstop

client/lib/application/src/approval-form/approval-card.jsx, client/lib/application/src/approval-form/approval-form.jsx, client/lib/application/src/router.react.jsx, client/lib/common/asset/less/application/approval-card.less, client/lib/common/asset/less/base.less, package.json, server/mocks/5000-kio.js, server/mocks/5009-user.js
=> 300 approval avatars

client/lib/common/src/data/fullstop/fullstop-types.js, client/lib/common/src/data/notification/notification-store.js, client/lib/common/src/data/twintip/twintip-actions.js, client/lib/common/src/data/twintip/twintip-getter.js, client/lib/common/src/data/twintip/twintip-store.js, client/lib/common/src/data/twintip/twintip-types.js, client/lib/common/src/util.js, client/lib/common/test/bootstrap.js, client/lib/common/test/fullstop/fullstop-getter.test.js, client/lib/common/test/twintip/twintip-store.test.js
=> #290 redux-ify twintip store

client/lib/common/src/data/fullstop/fullstop-actions.js, client/lib/common/src/data/notification/notification-actions.js, client/lib/common/src/data/team/team-actions.js, client/lib/common/src/data/team/team-getter.js, client/lib/common/src/data/team/team-store.js, client/lib/common/src/data/team/team-types.js, client/lib/common/src/data/twintip/twintip-actions.js, client/lib/common/src/data/user/user-actions.js, client/lib/common/src/data/user/user-getter.js, client/lib/common/src/data/user/user-store.js, client/lib/common/src/data/user/user-types.js, client/lib/common/test/bootstrap.js, client/lib/common/test/fullstop/fullstop-actions.test.js, client/lib/common/test/team/team-actions.test.js, client/lib/common/test/team/team-store.test.js, client/lib/common/test/user/user-getter.test.js, client/lib/common/test/user/user-store.test.js
=> 289 redux team user

client/lib/common/src/data/pierone/pierone-actions.js, client/lib/common/src/data/pierone/pierone-getter.js, client/lib/common/src/data/pierone/pierone-store.js, client/lib/common/src/data/pierone/pierone-types.js, client/lib/common/test/pierone/pierone-actions.test.js, client/lib/common/test/pierone/pierone-store.test.js
=> #287 redux pierone

client/lib/common/src/data/search/search-actions.js, client/lib/common/src/data/search/search-getter.js, client/lib/common/src/data/search/search-store.js, client/lib/common/src/data/search/search-types.js, client/lib/common/test/search/search-store.test.js, client/lib/yourturn/src/search/search.jsx
=> #288 redux search

client/lib/common/src/data/mint/mint-actions.js, client/lib/common/src/data/mint/mint-getter.js, client/lib/common/src/data/mint/mint-store.js, client/lib/common/src/data/mint/mint-types.js, client/lib/common/test/mint/mint-actions.test.js, client/lib/common/test/mint/mint-store.test.js
=> #285 redux mint

client/lib/common/src/data/essentials/application-store.js, client/lib/common/src/data/essentials/essentials-actions.js, client/lib/common/src/data/essentials/essentials-getter.js, client/lib/common/src/data/essentials/essentials-store.js, client/lib/common/src/data/essentials/essentials-types.js, client/lib/common/src/data/essentials/resource-store.js, client/lib/common/src/data/essentials/scope-store.js, client/lib/common/test/bootstrap.js, client/lib/common/test/essentials/application-store.test.js, client/lib/common/test/essentials/essentials-actions.test.js, client/lib/common/test/essentials/essentials-getter.test.js, client/lib/common/test/essentials/essentials-store.test.js, client/lib/common/test/essentials/resource-store.test.js, client/lib/common/test/essentials/scope-store.test.js
=> #282 redux essentials

client/lib/application/src/application-detail/application-detail.jsx, client/lib/application/src/application-form/application-form.jsx, client/lib/application/test/application-detail.test.js, client/lib/common/asset/less/application/application-detail.less, server/mocks/5000-kio.js
=> publicly accessible flag

client/lib/common/src/data/fullstop/fullstop-actions.js
=> #320 resurrect deleteViolations

client/Gulpfile.js, client/lib/common/src/data/fullstop/fullstop-actions.js, client/lib/common/src/data/fullstop/fullstop-getter.js, client/lib/common/src/data/fullstop/fullstop-store.js, client/lib/common/src/data/fullstop/fullstop-types.js, client/lib/common/src/lodash.custom.js, client/lib/common/src/util.js, client/lib/common/test/fullstop/fullstop-actions.test.js, client/lib/common/test/fullstop/fullstop-store.test.js, client/lib/violation/src/router.react.jsx, client/lib/violation/src/violation-list/violation-list.jsx, package.json
=> 328 shareable state accounts

build.sh, client/Gulpfile.js, client/lib/common/asset/less/common/account-selector.less, client/lib/common/src/lodash.custom.js, client/lib/violation/src/account-selector.jsx, client/lib/violation/src/violation-analysis/violation-analysis.jsx
=> 314 add all accounts

client/lib/common/asset/less/yourturn/notification-bar.less, client/lib/common/src/data/notification/notification-actions.js, client/lib/violation/src/router.react.jsx, client/lib/violation/src/violation-list/violation-list.jsx, client/lib/yourturn/src/app.jsx, package.json
=> #336 sharing URLs

client/lib/application/src/approval-form/approval-form.jsx, client/lib/common/asset/less/button.less, client/lib/common/asset/less/violation/violation-list.less, client/lib/common/src/data/fullstop/fullstop-actions.js, client/lib/common/src/data/fullstop/fullstop-store.js, client/lib/violation/src/router.react.jsx, client/lib/violation/src/violation-list/violation-list.jsx
=> 304 filter options

client/lib/common/asset/less/common/account-selector.less, client/lib/common/asset/less/common/collapsible.less, client/lib/common/src/collapsible.jsx, client/lib/violation/src/account-selector.jsx
=> collapse untoggled accounts

client/lib/common/asset/less/common/sortable-table.less, client/lib/common/asset/less/violation/violation-analysis.less, client/lib/common/src/sortable-table.jsx, client/lib/violation/src/router.react.jsx, client/lib/violation/src/violation-analysis/violation-analysis.jsx, client/lib/violation/src/violation-list/violation-list.jsx
=> #331 plot violations grouped by account

client/lib/violation/src/violation-list/violation-list.jsx
=> #343 use shorter url for sharing

client/lib/violation/src/violation-list/violation-list.jsx, client/lib/violation/src/violation-overview-account/violation-overview-account.jsx
=> #346 plot violations per app and violation type

client/lib/common/asset/less/common/account-selector.less, client/lib/common/asset/less/common/collapsible.less, client/lib/common/asset/less/violation/violation-list.less, client/lib/common/src/collapsible.jsx, client/lib/violation/src/account-selector.jsx, client/lib/violation/src/violation-analysis/violation-analysis.jsx, client/lib/violation/src/violation-list/violation-list.jsx, client/lib/violation/src/violation-overview-account/violation-overview-account.jsx, package.json
=> #349 collapsible filter and general styling

client/lib/common/src/util.js, client/lib/violation/src/router.react.jsx, client/lib/violation/src/violation-analysis/violation-analysis.jsx, client/lib/violation/src/violation-card/violation-card.jsx, client/lib/violation/src/violation-detail/violation-detail.jsx, client/lib/violation/src/violation-overview-account/violation-overview-account.jsx, client/lib/violation/src/violation/violation.jsx
=> fix violation router bugs

client/lib/common/src/data/fullstop/fullstop-actions.js, client/lib/common/src/data/fullstop/fullstop-store.js, client/lib/violation/src/router.react.jsx, client/lib/violation/src/violation/violation.jsx
=> #354 change sort order

client/lib/application/src/application-form/application-form.jsx, client/lib/application/src/approval-form/approval-form.jsx, client/lib/application/src/version-form/version-form.jsx, client/lib/common/asset/less/common/markdown.less, client/lib/common/asset/less/form.less, client/lib/common/src/markdown.jsx, client/lib/resource/src/resource-form/resource-form.jsx, client/lib/resource/src/scope-form/scope-form.jsx, client/mocha-globals.js
=> md preview

client/lib/application/src/application-form/application-form.jsx
=> require http(s) URLs for application masterdata

client/lib/application/src/router.react.jsx
=> require account information to be loaded

client/lib/application/src/approval-form/approval-form.jsx
=> #369 move toggle buttons on top, collapse notes by default

client/lib/application/src/version-detail/version-detail.jsx
=> #371 fix app version link in version detail

client/lib/violation/src/violation-overview-account/violation-overview-account.jsx
=> wrap chart render in if

client/lib/application/src/application-list/application-list.jsx, client/lib/application/src/router.react.jsx, client/lib/application/test/application-list.test.js, server/mocks/5000-kio.js
Fixes #372
Do it only when they are requested to be shown.
=> do not fetch versions for inactive apps initially

client/lib/common/asset/less/base.less, client/lib/common/asset/less/yourturn/search.less, client/lib/common/src/data/search/search-getter.js, client/lib/common/test/search/search-store.test.js, client/lib/yourturn/src/search/search.jsx, server/mocks/5000-kio.js
=> group search results

client/lib/common/src/sortable-table.jsx, client/lib/violation/src/router.react.jsx, client/lib/violation/src/violation-analysis/violation-analysis.jsx, client/lib/violation/src/violation/violation.jsx
Fixes #393
* Click on "Count" links to violation list with preset filters
* Sort config of table is persisted in URL so back button fully works
=> 393 direct link to violation list

Dockerfile, server/src/middleware/oauth.js, server/src/yourturn.js
=> oauth token verification middleware

client/lib/common/src/data/fullstop/fullstop-store.js, client/lib/violation/src/router.react.jsx
=> add default params in transitionTo hook

client/lib/violation/src/violation-card/violation-card.jsx, client/lib/violation/src/violation-detail/violation-detail.jsx, client/lib/violation/src/violation/violation.jsx
=> display account name in violation card

client/lib/common/src/data/fullstop/fullstop-store.js
=> change visual state on violation resolve

client/lib/common/src/data/team/team-actions.js, client/lib/common/src/data/team/team-getter.js, client/lib/common/src/data/team/team-store.js, client/lib/common/src/data/team/team-types.js, client/lib/common/src/sortable-table.jsx, client/lib/violation/src/router.react.jsx, client/lib/violation/src/violation-analysis/violation-analysis.jsx, client/lib/violation/src/violation/violation.jsx, server/mocks/5005-team.js, server/src/routes/team.js, server/src/yourturn.js
=> display team for account

.gitignore, client/lib/common/asset/less/violation/violation.less, client/lib/common/src/data/fullstop/fullstop-actions.js, client/lib/common/src/data/fullstop/fullstop-store.js, client/lib/violation/src/router.react.jsx, client/lib/violation/src/util.js, client/lib/violation/src/violation/violation-table.jsx, client/lib/violation/src/violation/violation.jsx, package.json
=> 429 paging options

Dockerfile
4.2 in anticipation of appdynamics which will not support 5.x. also
update node-tokens.
=> #420 stups/docker-node

client/lib/common/asset/less/common/badge.less, client/lib/common/asset/less/violation/violation.less, client/lib/common/src/badge.jsx, client/lib/common/src/data/fullstop/fullstop-actions.js, client/lib/common/src/data/fullstop/fullstop-store.js, client/lib/common/src/data/user/user-store.js, client/lib/violation/src/router.react.jsx, client/lib/violation/src/util.js, client/lib/violation/src/violation-card/violation-card.jsx, client/lib/violation/src/violation-viz.jsx, client/lib/violation/src/violation/violation-filters.jsx, client/lib/violation/src/violation/violation-table.jsx
=> #427 show whitelisted column, filter disabled accounts

server/src/middleware/oauth.js
=> #416 check realms

client/lib/violation/src/violation/violation-table.jsx, package.json
=> #432 tooltips for violation types

client/lib/violation/src/violation-card/violation-card.jsx, client/lib/violation/src/violation/violation-table.jsx, client/lib/violation/src/violation/violation.jsx
=> #433 close violation card by outside click

client/lib/common/asset/less/variables.less, client/lib/common/asset/less/violation/violation-card.less, client/lib/common/asset/less/violation/violation.less, client/lib/common/src/data/fullstop/fullstop-actions.js, client/lib/common/src/data/fullstop/fullstop-store.js, client/lib/violation/src/router.react.jsx, client/lib/violation/src/util.js, client/lib/violation/src/violation-card/violation-card.jsx, client/lib/violation/src/violation-viz.jsx, client/lib/violation/src/violation/filter-dropdown.jsx, client/lib/violation/src/violation/violation-filters.jsx, client/lib/violation/src/violation/violation-table.jsx
=> #435 abstract severity

client/lib/common/src/data/essentials/essentials-actions.js, client/lib/resource/src/resource-form/resource-form.jsx
=> allow dot in resource types

client/lib/application/src/application-detail/application-detail.jsx, client/lib/application/src/application-detail/placeholder.jsx, client/lib/application/src/application-form/application-form.jsx
=> #228 add specification_type field

client/lib/violation/src/violation/violation-filters.jsx
=> #450 reset page parameter after filter update

client/lib/violation/src/violation/filter-dropdown.jsx
Fixes #448 
Throw away state altogether.
=> #448 do not attempt to keep state with hidden dropdown

client/lib/common/src/data/fullstop/fullstop-store.js, client/lib/violation/src/violation/violation-table.jsx, server/mocks/fullstop-violations.json
Fixes #447 
* Explicitly sets `application_id` and `version_id`
* Updates test data
=> #447 update test data, add safeguards against old violations

client/Gulpfile.js, client/index.html, client/lib/common/src/data/essentials/essentials-getter.js, client/lib/common/src/data/user/user-getter.js, client/lib/common/src/lodash.custom.js, client/lib/common/src/router-utils.js, client/lib/common/test/essentials/essentials-getter.test.js, client/lib/resource/src/resource-detail/resource-detail.jsx, client/lib/resource/src/resource-form/resource-form.jsx, client/lib/resource/src/resource-list/resource-list.jsx, client/lib/resource/src/router.react.jsx, client/lib/resource/src/scope-detail/scope-detail.jsx, client/lib/resource/src/scope-form/scope-form.jsx, client/lib/resource/src/util.js, client/lib/resource/test/resource-detail.test.js, client/lib/resource/test/resource-form.test.js, client/lib/resource/test/resource-list.test.js, client/lib/resource/test/scope-detail.test.js, client/lib/resource/test/scope-form.test.js, client/lib/yourturn/src/bootstrap.jsx, package.json
Fixes #440 
* If part before first dot in resource type is an existing app, verify it's of the user's team
* If app does not exist, fall back to whitelisting
=> Change scope permissions

client/lib/application/src/router.react.jsx, client/lib/common/src/data/kio/application-store.js, client/lib/common/src/data/kio/kio-getter.js
=> Fix tab accounts not loading

.zappr.yaml
=> Make zapprfile the zalando-way

client/lib/application/src/router.react.jsx, server/mocks/5000-kio.js
=> Edit app form: Team IDs and previous value

client/lib/application/src/router.react.jsx
=> #475 try to fix the allScopes problem

server/src/yourturn.js
=> Change log format

client/lib/yourturn/src/notification-bar/notification-bar.jsx
the cycle check for removing old notifications is now only performed if there are notifications that might be removed due to age
=> #484 check for notifications only if there are notification are present

client/lib/application/src/version-detail/scm-source-warning.jsx, client/lib/application/src/version-detail/version-detail.jsx, client/lib/application/test/access-form.test.js, client/lib/application/test/application-detail.test.js, client/lib/application/test/application-form.test.js, client/lib/application/test/approval-form.test.js, client/lib/application/test/oauth-form.test.js, client/lib/application/test/version-detail.test.js, client/lib/application/test/version-form.test.js, client/lib/resource/test/resource-form.test.js, client/lib/resource/test/scope-form.test.js
added some PropTypes to some test setup
and found some not required PropTypes in some components
=> 490 adopt tests due to prop type changes

client/lib/application/src/router.react.jsx, client/lib/common/src/router-utils.js
Fix linter errors, somehow Travis did not report them, but our internal GoCD did.
=> Create team with account access

client/.eslintrc
This hopefully fixes eslint on all our systems.
=> Fix ESLint config

client/lib/common/asset/less/violation/date-dropdown.less, client/lib/violation/src/violation/date-dropdown.jsx, client/lib/violation/src/violation/violation-filters.jsx
fixed short links and layouting in date picker popup
=> #502 fixed short links in date picker. fixed layouting of date picker

Dockerfile
=> update docker base image

Dockerfile
There were many patches announced recently.
=> Update Dockerfile for OpenSSL

Dockerfile, client/lib/common/src/data/kio/kio-getter.js
=> /www/dist must be writable

server/package.json, server/src/env.js
=> Kubernetes support: read client-id from file

client/lib/application/src/approval-form/approval-form.jsx, client/lib/application/src/version-detail/version-detail.jsx, client/lib/application/src/version-list/version-list.jsx, client/lib/common/src/components/DeprecationWarning.jsx, client/lib/yourturn/src/app.jsx
=> #534 added deprecation warning

client/lib/application/src/oauth-form/oauth-form.jsx
=> Replace 'non-confidential' with RFC DL.

server/src/routes/user.js
* returning k8s accounts additionally to the aws accounts the user has access to
=> #539 returning additionally k8s accounts the user has access to

client/lib/application/src/cluster-list.jsx, client/lib/application/src/folded-scope-list.jsx
fixing cluster and scope filtration
=> fixing cluster and scope filtration

MAINTAINERS, client/lib/application/src/folded-scope-list.jsx
=> fix scopes filtration

client/lib/application/src/access-form/access-form.jsx, client/lib/application/src/folded-scope-list.jsx
fixing incorrect merge of props, fixing mint 400 error
=> fixing incorrect merge of props, fixing mint 400 error

client/lib/application/src/access-form/access-form.jsx, client/lib/application/src/folded-scope-list.jsx, client/lib/application/test/folded-scope-list.test.jsx, server/mocks/5003-essentials.js
=> 281 better scopes experience

server/src/yourturn.js
=> fix env vars

client/lib/common/src/data/user/user-actions.js, server/mocks/5006-tokeninfo.js, server/src/middleware/oauth.js, server/src/routes/tokeninfo.js, server/src/yourturn.js
Signed-off-by: Dmytro Bukhanets <dmytro.bukhanets@zalando.de>
=> using post instead of get for tokeninfo

client/lib/application/src/application-form/application-form.jsx
Change form to talk about application tiers.
=> Application Tiers

client/lib/application/src/application-detail/application-detail.jsx, client/lib/application/src/application-detail/placeholder.jsx, client/lib/common/asset/less/application/application-detail.less
Fix CSS to render Tier-1 as red and Tier-4 ("not relevant") as gray.
=> fix tier display (Tier-1 is most critical)

client/lib/application/src/application-form/application-form.jsx
* URLs must start with `https://`
* git repos should not have the `.git` in the URL
* remove the specification type field (not used)
=> validation should match application reviews

client/lib/application/src/application-form/application-form.jsx
Part of the solution for Problem described [here](https://github.bus.zalan.do/pitchfork/issues/issues/16) (Internal link)
=> Alert when user unchecks `Active Application`

Dockerfile
refs [internal](https://github.bus.zalan.do/pitchfork/issues/issues/138) issue
=> Update Dockerfile to use compliant Docker Image
